__author__ = 'RLT&LICE'
__version__ = '0.3.15'
__copyright__ = 'Copyright @ 2024 RLT&LICE'
__email__ = 'inco.k.b.blizz@gmail.com'
__url__ = 'https://github.com/Lice22R/DiscordBot'
__description__ = 'Дискорд бот управления ролями для канала Anafema'
